version: 1.0.{build}

environment:
  packageVersion: 1.0

init:
- ps: $env:buildVersion = "$env:packageVersion.$env:APPVEYOR_BUILD_NUMBER"
- ps: $env:nugetVersion = "$env:packageVersion-beta-$env:APPVEYOR_BUILD_NUMBER"
- ps: Update-AppveyorBuild -Version $env:buildVersion
- echo This is batch
- echo $(buildVersion)
- echo $(nugetVersion)

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(buildVersion)
  assembly_file_version: $(buildVersion)
  assembly_informational_version: $(nugetVersion)

configuration: Release

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

platform: Any CPU

clone_folder: C:\Projects\Parallel.Test.Framework

before_build:
- choco install codecov
- nuget restore
build_script:
- cmd: >-   

    msbuild Parallel.Test.Framework.sln /p:Configuration=Release

after_build:
- nuget pack ./Parallel.Test.Framework/Parallel.Test.Framework.nuspec -version $(nugetVersion)

artifacts:
- path: 'Parallel.Test.Framework*.nupkg'
  name: nuget-package
  
test_script:
- cmd: C:\Projects\Parallel.Test.Framework\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:aadhithB -target:"packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" -targetargs:"c:\Projects\Parallel.Test.Framework\Parallel.Test.FrameworkTests\bin\Release\Parallel.Test.FrameworkTests.dll" -output:".\coverage.xml" -filter:"+[Parallel.Test.Framework*]* -[Parallel.Test.FrameworkTests*]*"
- C:\Projects\Parallel.Test.Framework\packages\Codecov.1.0.3\tools\codecov.exe -f C:\Projects\Parallel.Test.Framework\coverage.xml -t f9537881-dd22-4e98-878f-47d7643499bf

deploy:
- provider: NuGet
  api_key:
    secure: WizYwPCkltrtJ69ioh2yUFx5gsYhAc2fMAMtjXieAuRbBg/MXENC06BjOTghqELx
  artifact: nuget-package
  on:
    branch: master
    
