version: 1.0.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#
environment:
  packageVersion: 1.0.0

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*' #'.\Parallel.Test.Framework\Properties\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

init:
- ps: $env:customBuildVersion = if ($env:APPVEYOR_REPO_TAG -eq $True) { "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_BUILD_NUMBER" } else { "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_BUILD_NUMBER-$env:APPVEYOR_REPO_BRANCH" }
- ps: $env:customNugetVersion = if ($env:APPVEYOR_REPO_TAG -eq $True) { "$env:APPVEYOR_BUILD_VERSION" } else { "$env:APPVEYOR_BUILD_VERSION" } #--else { "$env:APPVEYOR_BUILD_VERSION-pre" }
- ps: Update-AppveyorBuild -Version $env:customBuildVersion
 
 
# build cache to preserve files/folders between builds
cache:
 - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
 - '%LocalAppData%\NuGet\Cache'

# # Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
#                                   # account/project feeds for pull request builds

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU
#  - x86 , Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release
# Release, Debug

#clone_folder: C:\Projects\Parallel.Test.Framework

build:
  parallel: true                  # enable MSBuild parallel builds
  project: Parallel.Test.Framework.sln      # path to Visual Studio solution or project
  #publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
  #publish_wap_xcopy: true         # package Web Application Projects (WAP) for XCopy deployment
  #publish_azure: true             # package Azure Cloud Service projects and push to artifacts
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  #include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

  # MSBuild verbosity level
  #verbosity: quiet|minimal|normal|detailed
  verbosity: minimal

before_build:
- choco install codecov
- nuget restore Parallel.Test.Framework.sln

# # scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
# before_package:

# # scripts to run after build

build_script:
- cmd: >-   

    msbuild Parallel.Test.Framework.sln /p:Configuration=Release
   

before_package:
- ps: nuget pack ".\Parallel.Test.Framework\Parallel.Test.Framework.csproj" -properties Configuration=Release -Version $env:customNugetVersion
#nuget pack Parallel.Test.Framework.csproj -properties Configuration=Release -version 1.0.0.67
#- ps: nuget pack .\Parallel.Test.Framework\Parallel.Test.Framework.nuspec -Version $env:customNugetVersion

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
before_deploy:
- cmd: nuget pack ".\Parallel.Test.Framework\Parallel.Test.Framework.csproj" -properties Configuration=Release -Version $env:customNugetVersion


artifacts:
  # pushing all *.nupkg files in build directory recursively
- path: '**\Parallel.Test.Framework*.nupkg'
  name: Nuget
  
test_script:
- cmd: .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:aadhithB -target:"packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" -targetargs:".\Parallel.Test.FrameworkTests\bin\Release\Parallel.Test.FrameworkTests.dll" -output:".\coverage.xml" -filter:"+[Parallel.Test.Framework*]* -[Parallel.Test.FrameworkTests*]*"
- .\packages\Codecov.1.0.3\tools\codecov.exe -f .\coverage.xml -t f9537881-dd22-4e98-878f-47d7643499bf

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!


deploy:
- provider: NuGet
  name: nuget_release
  api_key:
    secure: WizYwPCkltrtJ69ioh2yUFx5gsYhAc2fMAMtjXieAuRbBg/MXENC06BjOTghqELx
  artifact: /.*\.nupkg/
  on:
    branch: master
    
